### ISSUE TITLE
How to add this extension with auto instrumentation

### ISSUE THREAD

**Issue by VelDeveloper** [vmaleze/opentelemetry-java-ignore-spans#1]
Hi, How to add this extension to the DockerFile which I already use aws-auto instrumentation? I am exactly looking for the solution this extension solves. Also, I want to ignore the liveness & readiness probe which generates more traces in k8s env. So it would be helpful if we could configure this to ignore URLs.

```
FROM amazoncorretto:17-alpine

RUN mkdir -p /agent
RUN apk update && apk add wget
RUN wget -O /agent/aws-opentelemetry-agent.jar https://github.com/aws-observability/aws-otel-java-instrumentation/releases/latest/download/aws-opentelemetry-agent.jar

ENV JAVA_TOOL_OPTIONS="-javaagent:/agent/aws-opentelemetry-agent.jar \
-Dotel.resource.attributes=service.name=sample-app,service.namespace=sample \
-Dotel.propagators=tracecontext \
-Dotel.traces.exporter=otlp \
-Dotel.metrics.exporter=otlp"


ARG JAR_FILE
COPY ${JAR_FILE} sample-app.jar
ENTRYPOINT ["java","-jar","/sample-app.jar"]
```

Any help would be really helpful.

**Comment by vmaleze** [comment]
Hello,

This extension is based on the default instrumentation. I don't know what is in the aws one. So this might not be suitable for you if the aws extension includes specific things.
If you still want to use this extension, you can simply replace your download instruction
`RUN wget -O /agent/aws-opentelemetry-agent.jar https://github.com/vmaleze/opentelemetry-java-ignore-spans/releases/download/1.2.0/opentelemetry-javaagent.jar`

I've also updated the extension so that you can set up your own list of spans to drop via an environment variable.
